version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  target-branch: master
  ignore:
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: karma-sauce-launcher
    versions:
    - 4.3.5
  - dependency-name: jasmine
    versions:
    - 3.6.4
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: chalk
    versions:
    - 4.1.0
  - dependency-name: handlebars
    versions:
    - 4.7.6
